import os

base_path = os.path.dirname(os.path.abspath(__file__))

stylesList = [
               {"styleImg": os.path.join(base_path, "style_imgs/AmericanGothic.jpg"),
                "name": "American Gothic - Grant Wood, 1930",
                "model": os.path.join(base_path, "models/models/AmericanGothic.pth")},
               {"styleImg": os.path.join(base_path, "style_imgs/ArnolfiniPortrait.jpg"),
                "name": "The Arnolfini Portrait - Jan van Eyck, 1434",
                "model": os.path.join(base_path, "models/models/ArnolfiniPortrait.pth")},
               {"styleImg": os.path.join(base_path, "style_imgs/CreationOfAdam.jpg"),
                "name": "Creation of Adam - Michelangelo, 1510",
                "model": os.path.join(base_path, "models/models/CreationOfAdam.pth")},
               {"styleImg": os.path.join(base_path, "style_imgs/diambraPainting.jpg"),
                "name": "Combate de mujeres - José de Ribera, 1636",
                "model": os.path.join(base_path, "models/models/diambraPainting.pth")},
               {"styleImg": os.path.join(base_path, "style_imgs/ImpressionSunrise.jpg"),
                "name": "Impression, Sunrise - Claude Monet, 1874",
                "model": os.path.join(base_path, "models/models/ImpressionSunrise.pth")},
               {"styleImg": os.path.join(base_path, "style_imgs/kandinsky.jpg"),
                "name": "Composition VII - Wassily Kandinsky, 1913",
                "model": os.path.join(base_path, "models/models/kandinsky.pth")},
               {"styleImg": os.path.join(base_path, "style_imgs/LadyErmine.jpg"),
                "name": "Lady with an Ermine - Leonardo da Vinci, 1490",
                "model": os.path.join(base_path, "models/models/LadyErmine.pth")},
               {"styleImg": os.path.join(base_path, "style_imgs/LibertyFrance.jpg"),
                "name": "Liberty Leading the People - Eugène Delacroix, 1830",
                "model": os.path.join(base_path, "models/models/LibertyFrance.pth")},
               {"styleImg": os.path.join(base_path, "style_imgs/MonaLisa.jpg"),
                "name": "Mona Lisa - Leonardo da Vinci, 1503",
                "model": os.path.join(base_path, "models/models/MonaLisa.pth")},
               {"styleImg": os.path.join(base_path, "style_imgs/mosaic.jpg"),
                "name": "Mosaic - Unknown",
                "model": os.path.join(base_path, "models/models/mosaic.pth")},
               {"styleImg": os.path.join(base_path, "style_imgs/PearlEarring.jpg"),
                "name": "Girl with a Pearl Earring - Johannes Vermeer, 1665",
                "model": os.path.join(base_path, "models/models/PearlEarring.pth")},
               {"styleImg": os.path.join(base_path, "style_imgs/persistenceOfMemory.jpg"),
                "name": "The Persistence of Memory - Salvador Dalí, 1931",
                "model": os.path.join(base_path, "models/models/persistenceOfMemory.pth")},
               {"styleImg": os.path.join(base_path, "style_imgs/picassoAvignon.jpg"),
                "name": "Les Demoiselles d'Avignon - Pablo Picasso, 1907",
                "model": os.path.join(base_path, "models/models/picassoAvignon.pth")},
               {"styleImg": os.path.join(base_path, "style_imgs/pollockN5.jpg"),
                "name": "No. 5, 1948 - Jackson Pollock, 1948",
                "model": os.path.join(base_path, "models/models/pollockN5.pth")},
               {"styleImg": os.path.join(base_path, "style_imgs/rainPrincess.jpg"),
                "name": "Rain Princess - Leonid Afremov",
                "model": os.path.join(base_path, "models/models/rainPrincess.pth")},
               {"styleImg": os.path.join(base_path, "style_imgs/RembrandtStorm.jpg"),
                "name": "The Storm on the Sea of Galilee - Rembrandt van Rijn, 1633",
                "model": os.path.join(base_path, "models/models/RembrandtStorm.pth")},
               {"styleImg": os.path.join(base_path, "style_imgs/SchoolAthens.jpg"),
                "name": "The School of Athens - Raphael, 1510",
                "model": os.path.join(base_path, "models/models/SchoolAthens.pth")},
               {"styleImg": os.path.join(base_path, "style_imgs/SundayAfternoon.jpg"),
                "name": "A Sunday Afternoon on the Island of La Grande Jatte - Georges Seurat, 1886",
                "model": os.path.join(base_path, "models/models/SundayAfternoon.pth")},
               {"styleImg": os.path.join(base_path, "style_imgs/TheKiss.jpg"),
                "name": "The Kiss - Gustav Klimt, 1907",
                "model": os.path.join(base_path, "models/models/TheKiss.pth")},
               {"styleImg": os.path.join(base_path, "style_imgs/Tsunami.jpg"),
                "name": "The Great Wave off Kanagawa - Hokusai, 1830",
                "model": os.path.join(base_path, "models/models/Tsunami.pth")},
               {"styleImg": os.path.join(base_path, "style_imgs/urloMunch.jpg"),
                "name": "The Scream - Edvard Munch, 1893",
                "model": os.path.join(base_path, "models/models/urloMunch.pth")},
               {"styleImg": os.path.join(base_path, "style_imgs/vangogh.jpg"),
                "name": "The Starry Night - Vincent van Gogh, 1889",
                "model": os.path.join(base_path, "models/models/vangogh.pth")},
               {"styleImg": os.path.join(base_path, "style_imgs/VenusBotticelli.jpg"),
                "name": "The Birth of Venus - Sandro Botticelli, 1485",
                "model": os.path.join(base_path, "models/models/VenusBotticelli.pth")}
             ]
